### ISSUE TITLE
Incorrect integer oveflow check in jpc_dec_process_siz() (jpc_dec.c)

### ISSUE THREAD

**Issue by thoger** [mdadams/jasper#119]
Commit d91198a was added in response to issue #49 to prevent integer overflow in the `jpc_dec_process_siz()` function in this multiplication: `dec->numhtiles * dec->numvtiles`.  The `jas_safe_size_mul()` is used to ensure that the product can fit into `size_t`.  After that, the value is assigned to `dec->numtiles = size;`.  However, as `numtiles` in `jpc_dec_t` is of type `int`, that assignment performs unsafe integer conversion to type of a smaller size (I'm assuming `sizeof(size_t) > sizeof(int)`, as is the case for current 64bit systems), resulting in value truncation.

So while the fix prevents overflow when one of the input values is negative, it does not catch all overflows.  Proper check would need to ensure that inputs are not negative and that their product fits into `INT_MAX`.

I have no reproducer for this problem, it was spotted while reviewing the above fix.

**Comment by mdadams** [comment]
I think that other checks in the code prevent the case of the values in question being negative, but I added assertions to ensure nonegativity as an extra precaution.  I also added a test to ensure that size does not exceed INT_MAX.  The bug fix is in commit a712a2041085e7cd5f2b153e1532ac2a2954ffaa.

**Comment by thoger** [comment]
At the time of d91198a, it was possible to have them negative - the test case in #49 demonstrated so for `numvtiles`.  In the current 2.0.11, that reproducer no longer reaches the relevant code in `jpc_dec_process_siz()` and is rejected by checks added in f7038068.

**Comment by mdadams** [comment]
Thank you for confirming that the negative-value case can no longer happen due to the other checks that I added in the other commit that you mentioned.
