### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by TeLLie** [mdadams/jasper#121]
Hello,

I compile it with cmake 3.7.0 and Gcc 4.9.2
We have no GL so thats disabled.
Makes runs fine till the end, so when running the tests that failed:

[C:\gcc-src\jasper-2.0.12\build1]ctest
Test project C:/Gcc-Src/jasper-2.0.12/build1
    Start 1: run_test_1
1/4 Test #1: run_test_1 .......................***Failed    0.12 sec
    Start 2: run_test_2
2/4 Test #2: run_test_2 .......................***Failed    0.21 sec
    Start 3: run_test_3
3/4 Test #3: run_test_3 .......................   Passed    0.09 sec
    Start 4: run_test_4
4/4 Test #4: run_test_4 .......................   Passed    0.09 sec

50% tests passed, 2 tests failed out of 4

Total Test time (real) =   0.57 sec

The following tests FAILED:
          1 - run_test_1 (Failed)
          2 - run_test_2 (Failed)
Errors while running CTest

Any idea how to fix this?

**Comment by mdadams** [comment]
It is impossible to diagnose the problem based on the extremely limited information that you have provlded.  If you can provide additional information that would help to pinpoint the problem, I will reopen this issue.

**Comment by brucellino** [comment]
Hello, I've also hit this. See https://github.com/SouthAfricaDigitalScience/jasper-deploy/issues/91

I appreciate the need for further information - from that issue, you can get to the build and the console log which caused the tests to fail.

If you could perhaps describe what the first two tests are doing - whether they need some input data or dependencies on the build host, that would help a lot.

Thanks !

**Comment by brucellino** [comment]
Upon some investigation, it seems like  the libjpeg library was missing. unconfirmed still.
