### ISSUE TITLE
cmake procedure confusing

### ISSUE THREAD

**Issue by DavidGriffith** [mdadams/jasper#132]
It's not at all clear how to use cmake to build jasper.  The stated directions: 
```
cmake -G "Unix Makefiles" -H$SOURCE_DIR -B$BUILD_DIR \
 -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR $OPTIONS
```
seem to suggest that ```$SOURCE_DIR``` should be ```./``` and ```$BUILD_DIR``` should be ```build```, but that doesn't work.  Nor does ```mkdir build; cd build; cmake ../``` work as with many other cmake-using programs.

The best I can come up with is at http://www.linuxfromscratch.org/blfs/view/8.0/general/jasper.html.  Following this leads to this complaint:
```
CMake Error: File /home/dave/proj/src/jasper/jasper.git/build/jasper.pc.in does not exist.
```

**Comment by mdadams** [comment]
There is a directory named "build" in the root of the JasPer source tree.  Don't try to use it as the build (i.e. binary) directory for cmake.  The build directory should be a directory that is not part of the source tree. In the example build instructions from the URL that you cited, the case of the directory name "BUILD" is important.  If you use lowercase ( i.e., "build"), you will try to build in a directory that is part of the source tree, which may cause problems.  Incidentally, you are also using an old version of JasPer.  The most recent version is 2.0.12 and can be downloaded here:
    http://www.ece.uvic.ca/~frodo/jasper/#download
The directions in the INSTALL file for JasPer do work, but use an undocumented feature of CMake, namely that the -H and -B options can be used to set both the source and build directories directly on the command line, respectively. (There cannot be spaces between option letters and their arguments (e.g., use "-Hdirname" not "-H dirname" in this usage).
