### ISSUE TITLE
name mismatch

### ISSUE THREAD

**Issue by maddin200** [mdadams/jasper#134]
libjasper\base\jas_cm.c line 99
declaration:
static int mono(jas_iccprof_t *prof,             int op, jas_cmpxformseq_t **pxformseq);
definition:
static int mono(jas_iccprof_t *iccprof,          int op, jas_cmpxformseq_t **retpxformseq)
{

**Comment by mdadams** [comment]
This is not a bug.  Strictly speaking, parameter names like "prof" are not part of a function declaration. They are ignored by the compiler.

**Comment by maddin200** [comment]
ok will not raise more like this
