### ISSUE TITLE
 Abort: Assertion `qmfbid == 0x01' failed.

### ISSUE THREAD

**Issue by xiaoqx** [mdadams/jasper#142]
An abort occurs when executing the following command:
jasper -f $FILE -t jpc -F /tmp/out.pnm -T pnm

jasper: /data/xqx/tests/libjasper-test/jasper/src/libjasper/jpc/jpc_t1cod.c:144: JPC_NOMINALGAIN: Assertion `qmfbid == 0x01' failed.
Aborted

testcase:
https://github.com/xiaoqx/pocs/blob/master/002-jasper-aborted-2

**Comment by asarubbo** [comment]
duplicate of #50

**Comment by jubalh** [comment]
@mdadams this one can be closed I think.

**Comment by mdadams** [comment]
@jubalh  Thank you for pointing out that this issue is now fixed.  I will close it now.
