### ISSUE TITLE
DLL function exports

### ISSUE THREAD

**Issue by tonytheodore** [mdadams/jasper#155]
Hi,

I notice there have been a few commits to export missing functions since v2:

https://github.com/mdadams/jasper/search?q=export&type=Commits

One of our ([MXE](http://mxe.cc)) users [reported some more missing `jp2*` functions](https://github.com/mxe/mxe/issues/1896) and I was wondering if adding `JAS_DLLEXPORT` to all public functions in a single sweep would be better than doing them [incrementally](https://gist.github.com/tonytheodore/9d369a754f0ea217fd11f22c7f3ef5ee)?

**Comment by mdadams** [comment]
Generally speaking, library users should not be directly calling internal functions in the library.  The only functions that should be exposed to the user start with the jas_ prefix.  Functions with the jp2_ prefix are internal implementation details of the JP2 codec and should not be invoked directly by the library user.

**Comment by tonytheodore** [comment]
Thanks, that makes sense.
