### ISSUE TITLE
Unable to compile Jasper 2.0.10 on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by winash12** [mdadams/jasper#163]
I am trying to compile Jasper 2.0.10 but I am getting  errors. I am able to compile Jasper 1.9.x which has the .configure script. But the CMAKE functionality is not clearly documented. These are the errors I get - 

This is the command I am using

cmake -G "Unix Makefiles" -H$SOURCE_DIR -B$BUILD_DIR \
      -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR $OPTIONS
I have H$SOURCE to be Hsrc which src is a directory under the jasper installation directory. Also I have a directory BUILD under the installation directory. Can you help me with the install ?

**Comment by mdadams** [comment]
You are setting SOURCE_DIR incorrectly.  It should be set to the top-level directory of the source tree (i.e., the directory containing the INSTALL and LICENSE files).  I have added a comment to the INSTALL documentation file to clarify this point in commit ed87dfc19429defcf1b628665e72d68aac0b283a.
