### ISSUE TITLE
Conan packages for Jasper

### ISSUE THREAD

**Issue by memsharded** [mdadams/jasper#170]
Hello!

I would like to report on the current status of the creation of packages and binary packages for Jasper:

- Created a package recipe here: https://github.com/conan-community/conan-jasper. The real recipe is: https://github.com/conan-community/conan-jasper/blob/master/conanfile.py, the rest are CI stuff
- Used travis-ci to build, test and upload packages for several flavors of Linux and OSX: https://travis-ci.org/conan-community/conan-jasper/builds/338930104
- Used appveyor to build, test and upload packages for several flavors in Windows: https://ci.appveyor.com/project/ConanCIintegration/conan-jasper/build/1.0.8
- Used the already existing package for libjpeg (``libjpeg/9b@bincrafters/stable``) in conan, as a requirement, so it is found in all platforms, and jasper provides libjpeg functionality
- Uploaded packages and binaries to bintray: https://bintray.com/conan-community/conan/jasper%3Aconan. The complete matrix is:

![jasper](https://user-images.githubusercontent.com/15367152/35972512-764735c6-0cd2-11e8-8e42-1cdcc586cf75.png)

That is more than 100 binaries for different configurations of static/shared, x86/x86_64 and different compiler versions and runtimes.

Everything is done for 2.0.14. It was relatively easy to setup, just learn about the different build options like JAS_ENABLE_SHARED and folder layout. I plan to submit it when possible for inclusion in the main central repo "conan-center", so feedback is really appreciated.

I will also try to keep updated and release also future versions, but in case you had some interest in taking over control of releasing conan packages, please tell me, once that it is setup, maintenance is really low.

**Comment by mdadams** [comment]
Thank you for the above information.  As best I can tell, however, this issue is not reporting a bug.  So, I am going to close this issue.
