### ISSUE TITLE
src/libjasper/jpc/jpc_util.c: 2 * bad test ?

### ISSUE THREAD

**Issue by dcb314** [mdadams/jasper#178]
jasper-2.0.14/src/libjasper/jpc/jpc_util.c:105]: (warning) Char literal compared with pointer 'cp'. Did you intend to dereference it?

Source code is

     while ((cp = strtok(0, delim))) {
                        if (cp != '\0') {

Maybe better code

     while ((cp = strtok(0, delim))) {
                        if (*cp != '\0') {

2.

jasper-2.0.14/src/libjasper/jpc/jpc_util.c:123]: (warning) Char literal compared with pointer 'cp'. Did you intend to dereference it?

Duplicate.

**Comment by mdadams** [comment]
I would concur that the original code looks rather insane.  I would agree that the code should say *cp instead of cp.  This fix has been applied in commit 573a6e47d45c9166331c115e78be962061c00bca.
