### ISSUE TITLE
Need to add -fPIC to Jasper compilation

### ISSUE THREAD

**Issue by winash12** [mdadams/jasper#181]
I am trying to compile gdal which has JASPER as a dependency. gdal wants JASPER to be compiled with -fPIC. Where in the compile process of JASPER can I add -fPIC ? The link of -fPIC with CMAKE is not clear.

**Comment by MaxKellermann** [comment]
Using `-DCMAKE_C_FLAGS=-fPIC`. This is a standard cmake option and has nothing to do with JasPer.
