### ISSUE TITLE
Package missing after Ubuntu 16.04

### ISSUE THREAD

**Issue by letmaik** [mdadams/jasper#185]
libjasper seems to have disappeared from the Ubuntu packages in recent versions: https://packages.ubuntu.com/search?keywords=libjasper-dev

I couldn't find information on why this happened and whether it will come back. Is this a known issue anyway?

**Comment by danieldjewell** [comment]
I'm not entirely sure why either ... 

Looks like as far as Ubuntu was concerned they were just following the upstream Debian package, so I'll reference that below. 

Here's some information from Debian that shows the status: 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862727 (Discussion on re-adding the package)

https://tracker.debian.org/pkg/jasper (Package history)

I suspect that a combination of factors were involved -- the [security vulnerabilities](https://security-tracker.debian.org/tracker/source-package/jasper) - which, granted, largely affected the version that Debian/Ubuntu was running (1.9) -- if you look at the Debian source package (https://packages.debian.org/source/jessie/jasper) there were all sorts of *individual* patches for the various vulnerabilities (CVEs). (Download the "debian.tar.xz" file to see the dpkg/debcontrol files - look in the patches directory to see.) 

The note from Moritz ([msg 50 on the debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862727#50)) indicates "we should stick with one implementation, namely openjpeg2"... 

And *that* package *is* there:

- [debian/source/sid/openjpeg2](https://packages.debian.org/source/sid/openjpeg2) 
- [ubuntu/source/bionic/openjpeg2](https://packages.ubuntu.com/source/bionic/openjpeg2)
- [ubuntu/source/cosmic/openjpeg2](https://packages.ubuntu.com/source/cosmic/openjpeg2)
- [ubuntu/source/disco/openjpeg2](https://packages.ubuntu.com/source/disco/openjpeg2)

However, if you have software that **requires** JasPer - then that seems like it's an issue. I'm not sure about the library compatibility of openjpeg2. 

Hope this helps! (I was trying to build software that needed JasPer but found a newer version that used either JasPer OR openjpeg2... seems that's the direction things are going)

**Comment by mdadams** [comment]
To the best of my recollection/understanding, Debian/Ubuntu decided to pull JasPer because 1.900.x had too many outstanding CVEs.  Many problems in JasPer were fixed between 1.900.x and the latest version, however. I tried to point this out at the time, but my comments had no effect.  I think that the only way that JasPer will be brought back to Debian/Ubuntu is if many users ask for it.
