### ISSUE TITLE
divide-by-zero in jpc_dec_process_siz (jpc_dec.c)

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#22]
Hello,
time ago I found multiple crashes on jasper. I didn't know where to post the bugs since the development seems dead, so I just informed the community on oss-security.
Now I discovered that the development is still active, here the details:

```
# imginfo $FILE
warning: trailing garbage in marker segment (2 bytes)
ASAN:DEADLYSIGNAL
=================================================================
==31103==ERROR: AddressSanitizer: FPE on unknown address 0x7f5b9237e7df (pc 0x7f5b9237e7df bp 0x7fff3818a0c0 sp 0x7fff38189fa0 T0)
    #0 0x7f5b9237e7de in jpc_dec_process_siz /tmp/jasper-version-1.900.3/src/libjasper/jpc/jpc_dec.c:1194:17
    #1 0x7f5b923842b2 in jpc_dec_decode /tmp/jasper-version-1.900.3/src/libjasper/jpc/jpc_dec.c:390:10
    #2 0x7f5b923842b2 in jpc_decode /tmp/jasper-version-1.900.3/src/libjasper/jpc/jpc_dec.c:254
    #3 0x7f5b92327a9a in jas_image_decode /tmp/jasper-version-1.900.3/src/libjasper/base/jas_image.c:372:16
    #4 0x4f11bd in main /tmp/jasper-version-1.900.3/src/appl/imginfo.c:179:16
    #5 0x7f5b9143f61f in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.22-r4/work/glibc-2.22/csu/libc-start.c:289
    #6 0x418bc8 in _start (/tmp/jasper-version-1.900.3/src/appl/.libs/imginfo+0x418bc8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /tmp/jasper-version-1.900.3/src/libjasper/jpc/jpc_dec.c:1194:17 in jpc_dec_process_siz
==31103==ABORTING
```

Tested against the latest 1.900.3
Testcase:
[11.crash.zip](https://github.com/mdadams/jasper/files/527229/11.crash.zip)

**Comment by mdadams** [comment]
This problem should now be fixed on the master branch. I added a check on the range of the XRsiz and YRsiz fields of the SIZ marker segment, which were missing.

**Comment by asarubbo** [comment]
Could you link the exactly commit which fixes the issue? thanks.

Note: if you are planning to make a release which fixes all security issues I reported, I would inform you that there is something else, but I will able to file the bugs on monday.

I'd like anyway to re-fuzz on a fixed release, thanks.

**Comment by mdadams** [comment]
I have made a new release with tag version-1.900.4 and I have also placed a corresponding gzipped tar archive on the jasper web site.  So, you can re-fuzz on this new release.

The particular commit that fixed the bug in this issue is given below.

commit d8c2604cd438c41ec72aff52c16ebd8183068020
Author: Michael Adams <mdadams@ece.uvic.ca>
Date:   Sat Oct 15 12:22:28 2016 -0700

    Added range check on XRsiz and YRsiz fields of SIZ marker segment.

M       src/libjasper/jpc/jpc_cs.c
