### ISSUE TITLE
assert in jpc_dec_tiledecode()

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#32]
The attached file causes an assert in the function jpc_dec_tiledecode. Found with american fuzzy lop.
[jasper-assert-jpc_dec_tiledecode.zip](https://github.com/mdadams/jasper/files/532164/jasper-assert-jpc_dec_tiledecode.zip)

Error message:
imginfo: jpc_dec.c:1072: int jpc_dec_tiledecode(jpc_dec_t *, jpc_dec_tile_t *): Assertion `dec->numcomps >= 3' failed.

**Comment by mdadams** [comment]
Fixed.  See commit 33cc2cfa51a8d0fc3116d16cc1d8fc581b3f9e8d.
