### ISSUE TITLE
--enable-debug should not enable sanitizers

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#36]
Usually --enable-debug stays for the debug assert.

Would be better have a different way to enable the sanitizers. See the libav way to enable them.
e.g:
./configure --toolchain={asan-gcc,ubsan-gcc,msan-gcc,asan-clang} and so on.

**Comment by mdadams** [comment]
I have added new configure options that can be used to enable various sanitizers:
--enable-usan
--enable-asan
--enable-leak
The processing of these options could probably be made more robust (e.g., check that the compiler supports the necessary options), but it is good enough for now, at least.
