### ISSUE TITLE
Fix build system for VPATH builds

### ISSUE THREAD

**Issue by SoapGentoo** [mdadams/jasper#37]
Hi @mdadams 
We recently got build failures in Gentoo, as we build jasper multilib aware, meaning using `-m32` for 32-bit libs and `-m64` for 64-bit libs. Unfortunately, the `jas_config.h` which is created in a separate build dir is never honoured. This in effect means that the build will only ever work when compiling in the source-tree. I've prepared a patch to always include the build tree before the source tree:
https://github.com/gentoo/gentoo/blob/master/media-libs/jasper/files/jasper-1.900.6-fix-build-system.patch

The issue is documented here:
https://bugs.gentoo.org/show_bug.cgi?id=597208

**Comment by mdadams** [comment]
I applied the patch provided without changes.  So, the problem should be fixed now. See:

commit 7489ff8a6adfba8bc305f6e988c799d1da73d7fa
Author: Michael Adams <mdadams@ece.uvic.ca>
Date:   Tue Oct 18 21:37:08 2016 -0700

    Applied fix for VPATH builds
