### ISSUE TITLE
mutiple implicit declaration of function

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#42]
After the compilation, I get these warnings:

```
 * /tmp/portage/media-libs/jasper-1.900.9/work/jasper-1.900.9/src/libjasper/base/jas_getopt.c:129:7: warning: implicit declaration of function 'jas_eprintf' is invalid in C99 [-Wimplicit-function-declaration]
 * /tmp/portage/media-libs/jasper-1.900.9/work/jasper-1.900.9/src/libjasper/jpc/jpc_tsfb.c:124:31: warning: implicit declaration of function 'jpc_tsfb_analyze2' is invalid in C99 [-Wimplicit-function-declaration]
 * /tmp/portage/media-libs/jasper-1.900.9/work/jasper-1.900.9/src/libjasper/jpc/jpc_tsfb.c:152:4: warning: implicit declaration of function 'jpc_tsfb_synthesize2' is invalid in C99 [-Wimplicit-function-declaration]
 * :243:6: warning: implicit declaration of function 'jas_eprintf' is invalid in C99 [-Wimplicit-function-declaration]
 * /tmp/portage/media-libs/jasper-1.900.9/work/jasper-1.900.9/src/libjasper/mif/mif_cod.c:282:3: warning: implicit declaration of function 'jas_eprintf' is invalid in C99 [-Wimplicit-function-declaration]
 * /tmp/portage/media-libs/jasper-1.900.9/work/jasper-1.900.9/src/libjasper/pnm/pnm_dec.c:121:3: warning: implicit declaration of function 'jas_eprintf' is invalid in C99 [-Wimplicit-function-declaration]
```

I need to investigate why at :243:6: there is no printed file....

**Comment by SoapGentoo** [comment]
These are fixed in my PR https://github.com/mdadams/jasper/pull/40

**Comment by mdadams** [comment]
I think that I have fixed the above warnings.  I changed configure earlier to use pedantic-errors and fixed what would no longer compile.  Please let me know if the above is not fixed.

Concerning #40: As far as I know, inttypes.h is not part of C99.  It appears to be POSIX/IEEE.   In any case, if the header file is not C99, I need to investigate the impact on other platforms like Windows.  I don't want to break the code on other non-POSIX platforms.

**Comment by SoapGentoo** [comment]
Wikipedia (https://en.wikibooks.org/wiki/C_Programming/C_Reference/inttypes.h) and the C99 standard (http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf) tell me that `inttypes.h` is a part of the standard.
