### ISSUE TITLE
segfault / null pointer access with malformed mif

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#44]
imginfo crashes by a simple MIF file only containing the two lines MIF and end.
Test:
```
echo -e "MIF\nend"|imginfo
```

[jasper-segfault-nullpointer.zip](https://github.com/mdadams/jasper/files/545285/jasper-segfault-nullpointer.zip)

**Comment by mdadams** [comment]
Already fixed on the master branch.  I think that this was a duplicate of another bug report (possibly from you).
