### ISSUE TITLE
assert triggered by malformed mif in pnm_getsint

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#47]
See attached file, found with afl.

Triggers an assert in imginfo:
imginfo: pnm_dec.c:397: int pnm_getsint(jas_stream_t *, int, int_fast32_t *): Assertion `(tmpval & (1 << (wordsize - 1))) == 0' failed.
[assert-pnm_getsint.zip](https://github.com/mdadams/jasper/files/546100/assert-pnm_getsint.zip)

**Comment by mdadams** [comment]
I have fixed the assertion.  The assertion was just flagging a feature that was not yet fully implemented.  The code now prints a message when it sees data that it cannot handle (or is out of range).  (It does not return with an error if PNM is in the mode where it tries to ignore errors.)  More importantly, the code does not crash any longer.  See commit e5b827c9611e43c704a1c4e33de21dea89d2145a.
