### ISSUE TITLE
abort on malformed mif

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#48]
This is actually a different issue from #43. Still present in the current git code.
[jasper-abort-new.zip](https://github.com/mdadams/jasper/files/546102/jasper-abort-new.zip)

The attached file causes an abort.

**Comment by mdadams** [comment]
Fixed.  See commit 5e3a597fb34cc8de8f67e02048bab492373bfe9e.
Note: The problem was actually in the PNM decoder, which is used by the MIF decoder.
Since PNM is used much more than MIF, it is particularly good that this problem was caught.
