### ISSUE TITLE
Definitions in jasper/jas_types.h conflict with libc headers

### ISSUE THREAD

**Issue by doughdemon** [mdadams/jasper#72]
`jasper/jas_types.h` contains definitions like:

```
#if !defined(uchar)
#define uchar unsigned char
#endif
```

So, `uchar` is defined as a macro, while most c libraries define `uchar` as a type.

Notice that the guard `#if !defined(uchar)` cannot detect whether `uchar` has already been defined as a type. So the macro in `<jasper/jas_types.h>` will override the libc definition.

On the other hand, if `<sys/types.h>` is included after `<jasper/jasper_types.h>` (but not before, even not indirectly), the macro definition will mangle libc's
```
typedef unsigned char uchar;
```
leading to a compilation error.

It seems that one way to fix this would be to replace the macro definitions by type definitions. I am not aware of any libc using macros to define ``uchar`` and friends, but if such exists, the existing ``#if``s could detect that. Note that It is allowed to ``typedef`` a type multiple times as long as the definitions agree.

**Comment by SoapGentoo** [comment]
@mdadams is there any reason to use `uchar`? Wouldn't `uint8_t` from `stdint.h` by much better and clearer (and more robust)?

**Comment by doughdemon** [comment]
There are also `ushort`, `uint` and `ulong`, which don't directly map
to stdint types.

However, these abbreviated types don't seem to be used consistently in
the code base. Maybe they could just be converted to their standard
long forms everywhere, so that the type definitions can be removed.

**Comment by gagern** [comment]
I noticed the `ushort`, `uint` and `ulong` first, in [Gentoo bug 599180](https://bugs.gentoo.org/show_bug.cgi?id=599180). Looking closer I found that [the corresponding `AC_CHECK_TYPE` calls](https://github.com/mdadams/jasper/blob/version-1.900.22/configure.ac#L325-L331) were using an [obsolete form]([Obsolete Macros](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html#Obsolete-Macros)) of the macro. The [modern form](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Generic-Types.html) does not perform any implicit action, just defines a macro like `HAVE_USHORT`. So the header would be free to `typedef` (preferred) or `#define` (problematic) any required types based on these flags. Or just `typedef` them unconditionally as suggested above.

Another aspect to this is that the `jasper.h` header is polluting the global namespace by including `jas_config.h` and `jas_types.h`. A *public library header* has in my opinion no business to declare preprocessor macros like `PACKAGE_NAME` or `ushort`. It should be careful to only declare things which are part of its public interface, with names prefixed by the name of the library. I'd say all public header files should make use of long names like `unsigned short`, and leave the abbreviations for internal code. Or `typedef … jas_ushort` if you must. Internal code could then `#include "config.h"` and configure could do whatever it wants to do.

At least on my system, the `-std=c11` option added by the configure script will prevent `sys/types.h` from declaring types like `ushort` and so on. A user not using this flag will get the `typedefs` from there. My message here is that it's bad style to include the results from feature checks into the public headers, as the availability of said features depends on many other things, including compiler settings.

**Comment by mdadams** [comment]
I agree with the sentiments expressed above.  JasPer should not be polluting the global namespace with identifiers not prefixed by JAS_ or jas_.  I have now made some major changes to the way in which the jas_config.h file is generated.  I also made a number of other changes to address other related issues.  Hopefully, I didn't break things too badly for anyone by making these changes.  I could not find a particularly good way to do what I wanted with the autotools, so I improvised. ;)  The result seems to work okay, but it is not the most elegant.  Also, I hope that nobody was relying on the cruft that was in jas_config.h that actually should not have been there.  If anyone was, their code will no longer compile.

My code changes can be found in the newly tagged release version-1.900.25.  Please give it a try and let me know if you have any problems.  I am marking this issue closed, but I can re-open it if you still have problems.
